tests: fix cases
jooby-dev/jooby-gui pull request #53
Opened 2024-08-21 08:30 UTC by nickkbell

2024-08-22 08:08 UTC, DarkPark approved these changes

2024-08-22 09:01 UTC, aleks-and submitted a review, later dismissed

2024-08-30 07:55 UTC, DarkPark commented on tests/objects/MainPage.js
> +        return this.page.getByRole('link', {name: 'GitHub'})
```suggestion
        return this.page.getByRole('link', {name: 'GitHub'});
```

2024-08-30 07:58 UTC, DarkPark commented on tests/objects/MainPage.js
> +        return await this.page.locator('h5').allInnerTexts();
```suggestion
        return this.page.locator('h5').allInnerTexts();
```
and in other places

2024-09-02 07:21 UTC, DeadByElpy requested changes

2024-09-02 07:21 UTC, DeadByElpy commented on tests/specs/functional.spec.js
> +
```suggestion
```

2024-09-02 08:28 UTC, nickkbell commented
closed because not relevant

2024-09-02 08:28 UTC, closed without merging